### ISSUE TITLE
liberation-fonts-ttf-2.00.1: No such file or directory

### ISSUE THREAD

**Issue by simonbcn** [julroy67/kagayaki#11]
```
Making package: ttf-liberation-kagayaki 2.00.1-2 
...
==> Starting package()...
/home/juan/fuentes/kagayaki/fonts/extended/ttf-liberation-kagayaki/PKGBUILD: line 29: cd: /tmp/makepkg/ttf-liberation-kagayaki/src/liberation-fonts-ttf-2.00.1: No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

Are you testing the changes after do them? The validate and these errors are easily detectable (_and fixable_) if you test the packages before upload them.

**Comment by julroy67** [comment]
Please update to 2.00.3 PKGBUILD as fixed in commit d7a38988d069ff105148b36e52641bf15e075e8a
As I'm using building the packages afterwards, yes I'm testing the changes before commiting.
