### ISSUE TITLE
validity checks

### ISSUE THREAD

**Issue by simonbcn** [julroy67/kagayaki#17]
With every update there are several: `ERROR: One or more files did not pass the validity check!`
Please, can you test the packages before update them?

**Comment by julroy67** [comment]
If upstream updates the zip file without changing the name of the file, I can't do anything. As of #18, upstream updated the zip file, changing the font version (1.005) and changing directory structure. The PKGBUILD was meant for the 1.004 version. Please understand that if the URL is not versioned i can't do anything to stop upstream from changing the content of the file. As of #19, it's sometime difficult to track makedepends when they are already installed locally.

But thanks anyway for reporting ;)
