### ISSUE TITLE
ttf-carlito-kagayaki: several errors

### ISSUE THREAD

**Issue by simonbcn** [julroy67/kagayaki#4]
`ttf-carlito-kagayaki: don't pass validity check`
After solve this:
`cd: carlito: No such file or directory`

**Comment by simonbcn** [comment]
ok, the problem is the change of URL for source of font from `http://mirrors.ctan.org/fonts/carlito.zip` to `http://commondatastorage.googleapis.com/chromeos-localmirror/distfiles/crosextrafonts-carlito-20130920.tar.gz`

**Comment by simonbcn** [comment]
#5

**Comment by julroy67** [comment]
Fixed in 6b261ce58d66a225f5a27367f5bfc5825e793880
