### ISSUE TITLE
ttf-noto-emoji: wrong size

### ISSUE THREAD

**Issue by simonbcn** [julroy67/kagayaki#8]
This is a github comment with emojis and `ttf-noto-emoji-kagayaki`:
![captura de pantalla de 2017-03-03 15-44-18](https://cloud.githubusercontent.com/assets/428231/23555354/e2d039b6-0028-11e7-8892-15e5847caaf6.png)

and this is the same comment without `ttf-noto-emoji-kagayaki`:
![captura de pantalla de 2017-03-03 15-45-07](https://cloud.githubusercontent.com/assets/428231/23555374/f8ccd454-0028-11e7-9d55-04d754886499.png)

Both on Firefox 51.0.1
Moreover, I think this font shouldn't be in base package.

**Comment by julroy67** [comment]
That's really strange, I can't reproduce it. Do you get a correct rendering on http://getemoji.com/ ?
Btw, it is already in the base group.

**Comment by simonbcn** [comment]
I think this font should **NOT** be in base package. It should be in _extra_ or better alone.

**Comment by simonbcn** [comment]
![get emoji-without-emoji-font](https://cloud.githubusercontent.com/assets/428231/23654516/506bf54a-0331-11e7-8af3-e3c300dbe952.png)
--------------------------------------------------------

![get emoji-with-emoji-font](https://cloud.githubusercontent.com/assets/428231/23654535/5fc6ce52-0331-11e7-8860-5701c8e062dd.png)

**Comment by simonbcn** [comment]
I've tested with the official package of [noto-emoji](https://www.archlinux.org/packages/extra/any/noto-fonts-emoji/) and it occurs too. I think the bug can be in Firefox.

**Comment by julroy67** [comment]
There is something wrong with Firefox, on Chromium it works as expected, but on Firefox I get some emojis, but not the one from Noto Color Emoji font. Are you using latest fontconfig and noto emoji PKGBUILDs ?

As I'm expecting to render emojis using the base config, I think Noto Emoji package belongs to base group.

![screencapture-getemoji-1488890408612](https://cloud.githubusercontent.com/assets/198724/23656878/cbc3815e-033b-11e7-8434-02d05e808b44.png)

**Comment by simonbcn** [comment]
Forget it. Firefox, since version 50, [brings native emoji](http://www.omgubuntu.co.uk/2016/11/firefox-50-brings-native-emoji-linux-desktops). I think it's a Firefox problem.
